server:
  port: 6160
  servlet:
    context-path: /dev

logging:
  # log4j2-dev.xml 配置文件提供骨架
  config: classpath:config/logging/log4j2-dev.xml
  # application.yml 进行精细控制
  level:
    thriving:
      softwood: trace

async:
  vt:
    thread-name-prefix: vt-exec-
    concurrency-limit: 300
  pt:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 500
    thread-name-prefix: pt-exec
    rejected-exec-handler-type: AbortPolicy